# === Название проекта и версия ===
project.name=opi3
project.version=1.0.0
main.class=org.example.web3.Main

# === Пути проекта ===
src.dir=src/main/java
test.dir=src/test/java
resources.dir=src/main/resources
webapp.dir=src/main/webapp
lib.dir=lib
build.dir=build
dist.dir=dist
doc.dir=doc
report.dir=reports
tmp.dir=tmp

# === Компиляция ===
compiler.source=17
compiler.target=17

# === Локализация/native2ascii ===
native.src.dir=${resources.dir}/locale
native.dest.dir=${build.dir}/locale

# === Музыка ===
music.file=music/success.mp3

# === SCP ===
scp.server=helios.cs.ifmo.ru
scp.user=s472548
scp.path=/home/studs/s472548/opi/lab3
scp.port=2222
scp.ssh.options=-o StrictHostKeyChecking=accept-new

# === Git: для team/history ===
# Для macOS Ant внутри history/team будет вызывать ant напрямую.
ant.executable=ant
git.previous.revisions=4
team.dir=${build.dir}/team
team.zip=${dist.dir}/team-revisions.zip
history.dir=${build.dir}/history
history.diff.file=${dist.dir}/history.diff

# === SVN: для report/diff, потому что в твоём условии эти targets работают с SVN ===
# Если проект лежит прямо в svn working copy, оставь точку.
svn.workdir=.
svn.report.path=${report.dir}

# === ALT: замены для альтернативной версии ===
replace.class.original=HitChecker
replace.class.new=AreaChecker
replace.main.class=org.example.web3.Main
replace.class.file.original=org/example/web3/HitChecker.java
replace.class.file.new=org/example/web3/AreaChecker.java
replace.variable.original=isHit
replace.variable.new=hitResult

# === DIFF: защищённые классы, которые нельзя менять для auto-commit в SVN ===
# Перечисляются через пробел.
diff.protected.class.1=src/main/java/org/example/web3/HitChecker.java
diff.protected.class.2=src/main/java/org/example/web3/beans/PointBean.java

# ENV
env.java21.home=/Users/artem/Library/Java/JavaVirtualMachines/ms-21.0.10/Contents/Home
env.java17.home=/Users/artem/Library/Java/JavaVirtualMachines/graalvm-jdk-17.0.12/Contents/Home
env.java21.args=-Xmx1024m -Xms512m -XX:+UseG1GC
env.java17.args=-Xmx1024m -Xms512m
